name: "Build and Test workflow"

on:
  push:
    branches:
        - "**"        # matches every branch
#        - "!main"   # excludes master
  pull_request:
    branches:
        - "main"
#        - "feature-dr"

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
        matrix:
            destination: ['platform=iOS Simulator,OS=15.5,name=iPhone 13 Pro Max']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build
        run: |
          xcodebuild clean build -project FundEd.xcodeproj -scheme FundEd -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env:
         destination: ${{ matrix.destination }}
     - name: Test
        run: |
          xcodebuild clean test -project FundEd.xcodeproj -scheme FundEdTests -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env:
         destination: ${{ matrix.destination }}
